version: '3.4'

services:
  kaleidocontracttemplates:
    image: [],
    build:
      context:
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
    command: ["node", "--inspect=10.32.0.0/27", "index.js"]
